# Generated by Django 4.1.7 on 2023-03-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_news',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(choices=[('AR', 'статья'), ('NE', 'новость')], default='AR', max_length=2),
        ),
    ]
